#!/usr/bin/env python3
"""Deterministic demoware scanner for Reality Skill.

This helper finds likely fake UI/workflow signals. It is intentionally
conservative: findings are leads for the agent to verify in code.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Iterable


TEXT_EXTENSIONS = {
    ".astro",
    ".css",
    ".html",
    ".js",
    ".jsx",
    ".mdx",
    ".svelte",
    ".ts",
    ".tsx",
    ".vue",
}

SKIP_DIRS = {
    ".git",
    ".next",
    ".nuxt",
    ".svelte-kit",
    "build",
    "coverage",
    "dist",
    "node_modules",
    "out",
    "vendor",
}


@dataclass(frozen=True)
class Rule:
    code: str
    severity: str
    gate: str
    pattern: str
    message: str


@dataclass
class Finding:
    path: str
    line: int
    code: str
    severity: str
    gate: str
    message: str
    evidence: str


RULES = [
    Rule("DEAD_HREF", "P0", "Action", r'href=["\']#["\']', "Dead anchor used as navigation."),
    Rule("CONSOLE_HANDLER", "P0", "Action", r"on\w+\s*=\s*\{?\s*\(?[^=\n]*\)?\s*=>\s*console\.log", "Event handler only logs to console."),
    Rule("ALERT_HANDLER", "P1", "Feedback", r"on\w+\s*=\s*\{?\s*\(?[^=\n]*\)?\s*=>\s*alert\(", "Action relies on alert instead of app state."),
    Rule("COMING_SOON", "P1", "Truth", r"\bcoming soon\b", "Unavailable capability must be disabled or scoped clearly."),
    Rule("TODO", "P2", "Verification", r"\bTODO\b|\bFIXME\b", "Unfinished implementation marker."),
    Rule("LOREM", "P2", "Data", r"lorem ipsum|dolor sit amet", "Placeholder copy/data."),
    Rule("MATH_RANDOM_METRIC", "P1", "Data", r"Math\.random\s*\(", "Random data can create fake metrics or fake behavior."),
    Rule("FAKE_TIMEOUT", "P1", "Action", r"setTimeout\s*\(", "Timeout-driven fake async behavior needs verification."),
    Rule("PLACEHOLDER", "P2", "Truth", r"\bplaceholder\b|\bdummy\b|\bfake\b", "Possible placeholder/fake boundary."),
    Rule("MOCK", "P2", "Truth", r"\bmock(?:ed)?\b|\bsample data\b", "Mock/sample boundary must be honest in UI."),
    Rule("FAKE_PAYMENT", "P0", "Truth", r"\b(pay now|payment successful|card charged|receipt)\b", "Payment claims require real provider or disabled/sandbox boundary."),
    Rule("FAKE_AUTH", "P0", "Truth", r"\b(oauth|sign in with|login successful|authenticated)\b", "Auth claims require real provider or explicit demo boundary."),
    Rule("FAKE_AI", "P0", "Truth", r"\b(generated by ai|ai generated|thinking\.\.\.|analyzing\.\.\.)\b", "AI claims require real model call or mock label."),
    Rule("FAKE_EXPORT", "P1", "Action", r"\b(export|download)\b", "Export/download actions must produce current data or be disabled."),
]


STRICT_RULES = [
    Rule("BUTTON_NO_HANDLER", "P1", "Action", r"<button(?![^>]*(onClick|type=[\"']submit[\"']|disabled))[^>]*>", "Button may have no handler, submit role, or disabled reason."),
    Rule("HASH_LINK", "P0", "Navigation", r"<a[^>]+href=[\"']#[^\"']*[\"']", "Hash-only link may be dead navigation."),
    Rule("SUCCESS_TOAST", "P1", "Feedback", r"\b(saved|sent|published|deployed|synced|invited|connected) successfully\b", "Success claim must match a real committed action."),
]


def iter_files(target: Path, include_docs: bool = False) -> Iterable[Path]:
    extensions = set(TEXT_EXTENSIONS)
    if include_docs:
        extensions.add(".md")

    if target.is_file():
        if target.suffix.lower() in extensions:
            yield target
        return

    for path in target.rglob("*"):
        if any(part in SKIP_DIRS for part in path.parts):
            continue
        if path.is_file() and path.suffix.lower() in extensions:
            yield path


def scan_file(path: Path, rules: list[Rule], root: Path) -> list[Finding]:
    findings: list[Finding] = []
    try:
        lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
    except OSError:
        return findings

    for index, line in enumerate(lines, start=1):
        for rule in rules:
            if re.search(rule.pattern, line, flags=re.IGNORECASE):
                findings.append(
                    Finding(
                        path=str(path.relative_to(root) if path.is_relative_to(root) else path),
                        line=index,
                        code=rule.code,
                        severity=rule.severity,
                        gate=rule.gate,
                        message=rule.message,
                        evidence=line.strip()[:180],
                    )
                )
    return findings


def summarize(findings: list[Finding]) -> dict[str, object]:
    counts: dict[str, int] = {}
    gates: dict[str, int] = {}
    for finding in findings:
        counts[finding.severity] = counts.get(finding.severity, 0) + 1
        gates[finding.gate] = gates.get(finding.gate, 0) + 1

    hard_fail = any(f.severity == "P0" for f in findings)
    return {
        "total": len(findings),
        "by_severity": counts,
        "by_gate": gates,
        "hard_fail": hard_fail,
        "decision": "BLOCKED" if hard_fail else "REVIEW_FINDINGS" if findings else "NO_DEMOWARE_SIGNALS_FOUND",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Scan for demoware signals.")
    parser.add_argument("--audit", dest="target", required=True, help="File or directory to scan.")
    parser.add_argument("--strict", action="store_true", help="Enable stricter, noisier UI heuristics.")
    parser.add_argument("--include-docs", action="store_true", help="Include Markdown documentation files.")
    parser.add_argument("--json", action="store_true", help="Emit JSON.")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    if not target.exists():
        raise SystemExit(f"Target does not exist: {target}")

    root = target if target.is_dir() else target.parent
    rules = RULES + (STRICT_RULES if args.strict else [])
    findings: list[Finding] = []
    for file_path in iter_files(target, include_docs=args.include_docs):
        findings.extend(scan_file(file_path, rules, root))

    payload = {
        "target": str(target),
        "strict": args.strict,
        "include_docs": args.include_docs,
        "summary": summarize(findings),
        "findings": [asdict(finding) for finding in findings],
    }

    if args.json:
        print(json.dumps(payload, indent=2))
        return 1 if payload["summary"]["hard_fail"] else 0

    summary = payload["summary"]
    print(f"Reality audit: {target}")
    print(f"Decision: {summary['decision']}")
    print(f"Findings: {summary['total']} | Severity: {summary['by_severity']} | Gates: {summary['by_gate']}")
    for finding in findings[:80]:
        print(
            f"{finding.severity} {finding.gate} {finding.path}:{finding.line} "
            f"{finding.code} - {finding.message} :: {finding.evidence}"
        )
    if len(findings) > 80:
        print(f"... {len(findings) - 80} more findings")
    return 1 if summary["hard_fail"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
